await loadScript("scripts/plugins/hydra-src.js")

s0.initCam(0)
s1.initCam(1)

// src(s1).noWrap()
srcRelMask(s1)
    .scale(0.3)
    .scroll(-0.3, -0.3)
    //   .rotateRel(1)
    // 	.kaleid(4)
    //     .scale(0.2)
    //     .rotate(1)
    //   .rotate(1)
    //   .rotateRel(1)
    //   .kaleid(4)
    //   .scale(0.2)
    //   .rotate(() => Math.sin(time))

    .add(srcRelMask(s0)
        .scale(0.3)
        .scroll(0.3, 0.3)
    ).out()
// .add(src(s0)).out()