await loadScript("scripts/plugins/hydra-src.js")
await loadScript("scripts/plugins/hydra-text.js")
await loadScript("scripts/plugins/hydra-mouse.js")
await loadScript("scripts/windows.js")

hydraText.font = "interceptor"
hydraText.lineWidth = "2%"

s0.initCam(0)
s1.initCam(1)
s2.initCam(2)

solid(1, 1, 1)
.diff(shape([4, 4, 4, 24].smooth()
.fast(.5), 0.95, .09)
.repeat(20, 10))
.color(0, 0.2, 0)
.modulateScale(osc(2)
.rotate(-0.5), .22)
.add(
    src(o0)
    .scale(0.965)
    .rotate(.012 * (Math.round(-2)))
    .color(0.1, 0.5, 0.1)
    .modulateRotate(o0, 0.5)
    .brightness(.05), .7)
.layer(srcRelMask(s0)
.scale(() => win.scale[0])
.rotate(() => Math.sin(time) / 30)
.scroll(() => win.x[0], () => win.y[0])
//     .modulate(src(s1))
)
.layer(srcRelMask(s0)
.scale(() => win.scale[1])
.rotate(() => Math.sin(time) / 30)
.scroll(() => win.x[1], () => win.y[1])
//     .modulate(src(s1))
)
// .layer(srcRelMask(s1)
//     .scale(0.3)
//     .scroll(0.3, 0.3)
//     .pixelate(200, 100)
// )
// .layer(srcRelMask(s2)
//     .scale(0.35)
//     .scroll(-0.1, 0.1)
//     .pixelate(200, 100)
// )
// .layer(text("Neon Move")
//     .color(0.1, 0.5, 0.1)
//     .scale(0.3)
//     .scroll(0.2, -0.2)
//     .modulate(voronoi())
//     .modulate(osc(1, 1, 1))
// )
.out()
